name: C-lang CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Valgrind
        run: sudo apt-get install valgrind -y

      - name: Make
        run: gcc --version && make valgrind
